---

# Время рестарта в минутах
# 3 часа => 60 * 3 => 180 минут
restart: 180

# Время очистки в минутах
clean: 30

restart-message: "Была выполнена перезагрузка"
clean-message: "Была выполнена очистка"
to-restart: "До перезагрузки осталось 5 минут"

...